import 'libs/common/src/shared/assets/styles/globals.scss'
import { ReactNode } from 'react'
import { LayoutAdminPanel } from '@magicbeauty/common/server'

export const metadata = {
  title: 'Welcome to admin-panel',
  description: 'Generated by create-nx-workspace'
}

export default function RootLayout({
                                     children
                                   }: {
  children: ReactNode
}) {
  return (
    <html lang='en'>
    <body>
    <LayoutAdminPanel>
      {children}
    </LayoutAdminPanel>
    </body>
    </html>
  )
}
