version: '3'

services:
  app:
    build:
      dockerfile: docker-files/Dockerfile.app
    restart: always
    ports:
      - '4200:4200'
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_CLIENT=${POSTGRES_CLIENT}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app
    depends_on:
      - db
  shop:
    build:
      dockerfile: docker-files/Dockerfile.shop
    restart: always
    ports:
      - '3217:3217'
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_CLIENT=${POSTGRES_CLIENT}
      - DATABASE_URL=${DATABASE_URL}
      - CLOUD_NAME=${CLOUD_NAME}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
    networks:
      - app
    depends_on:
      - db
  admin-panel:
    build:
      dockerfile: docker-files/Dockerfile.admin-panel
    restart: always
    ports:
      - '2321:2321'
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_CLIENT=${POSTGRES_CLIENT}
      - DATABASE_URL=${DATABASE_URL}
      - CLOUD_NAME=${CLOUD_NAME}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
    networks:
      - app
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '3423:5432'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_CLIENT=${POSTGRES_CLIENT}
    volumes:
      - /db/var/lib/postgresql/data
    networks:
      - app

networks:
  app:

volumes:
  db:
