version: '3'

services:
  app:
    build:
      dockerfile: docker-files/Dockerfile.app
    restart: always
    ports:
      - '4200:4200'
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_CLIENT=${POSTGRES_CLIENT}
      - DATABASE_URL=${DATABASE_URL}
      - CLOUD_NAME=${CLOUD_NAME}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
  shop:
    build:
      dockerfile: docker-files/Dockerfile.shop
    restart: always
    ports:
      - '3217:3217'
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_CLIENT=${POSTGRES_CLIENT}
      - DATABASE_URL=${DATABASE_URL}
      - CLOUD_NAME=${CLOUD_NAME}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
  admin-panel:
    build:
      dockerfile: docker-files/Dockerfile.admin-panel
    restart: always
    ports:
      - '2321:2321'
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_CLIENT=${POSTGRES_CLIENT}
      - DATABASE_URL=${DATABASE_URL}
      - CLOUD_NAME=${CLOUD_NAME}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
