export const SHOP_HOME_PAGE_URL = '/'
export const SHOP_CATEGORIES_PAGE_URL = '/categoris'
export const SHOP_ABOUT_PAGE_URL = '/about'
export const SHOP_NEWS_PAGE_URL = '/news'
export const SHOP_OPT_PAGE_URL = '/opt'
