export {ReactComponent as IconCart} from "./icons/cart.svg"
export {ReactComponent as IconPhone} from "./icons/phone.svg"
export {ReactComponent as IconBookmark} from "./icons/bookmark.svg"
export {ReactComponent as IconSearch} from "./icons/search.svg"
export {ReactComponent as IconClose} from "./icons/close.svg"
export {ReactComponent as IconPlus} from "./icons/plus.svg"
export {ReactComponent as IconLogoShop} from "./icons/logo-shop.svg"
