// Regex
export { regexMobileType, regexTabletType, emailRegex, digitRegex, symbolRegex, uppercaseRegex, minLengthRegex, lowercaseRegex, phoneRegex } from "./regex"

// Path pages
export {
  ADMIN_PANEL_HOME_PAGE_URL,
  ADMIN_PANEL_PRICE_AND_SIZE_PAGE_URL,
  ADMIN_PANEL_BANNER_PAGE_URL,
  ADMIN_PANEL_BRANDS_PAGE_URL,
  ADMIN_PANEL_POSTS_PAGE_URL,
  ADMIN_PANEL_GEL_POLISHES_PAGE_URL,
  SHOP_OPT_PAGE_URL,
  SHOP_HOME_PAGE_URL,
  SHOP_NEWS_PAGE_URL,
  SHOP_ABOUT_PAGE_URL,
  SHOP_CATEGORIES_PAGE_URL,
  ADMIN_PANEL_LANGUAGE_PAGE_URL,
  ADMIN_PANEL_CATEGORICAL_BUSINESS_CARDS_PAGE_URL
} from './path-pages'
