import './globals.scss'
import 'swiper/css'
import { LayoutShop } from '@magicbeauty/common/server'
import { ReactNode } from 'react'

export const metadata = {
  title: 'Welcome to shop',
  description: 'Generated by create-nx-workspace'
}

export default function RootLayout({
  children
}: {
  children: ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <LayoutShop>
          {children}
        </LayoutShop>
      </body>
    </html>
  )
}
