import 'libs/common/src/shared/assets/styles/globals.scss'
import {LayoutShop} from "@magicbeauty/common/server"

export const metadata = {
  title: 'Welcome to shop',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
    <body>
    <LayoutShop>
      {children}
    </LayoutShop>
    </body>
    </html>
  )
}
