export {
  ADMIN_PANEL_HOME_PAGE_URL,
  ADMIN_PANEL_PRICE_AND_SIZE,
  ADMIN_PANEL_BANNER_PAGE_URL,
  ADMIN_PANEL_BRANDS_PAGE_URL,
  ADMIN_PANEL_GEL_POLISHES_PAGE_URL
} from './path-pages-admin-panel'
