export const ADMIN_PANEL_HOME_PAGE_URL = '/'
export const ADMIN_PANEL_GEL_POLISHES_PAGE_URL = '/gel-polishes'
export const ADMIN_PANEL_BRANDS_PAGE_URL = '/brand'
export const ADMIN_PANEL_BANNER_PAGE_URL = '/banner'
export const ADMIN_PANEL_PRICE_AND_SIZE_PAGE_URL = '/price-and-size'
export const ADMIN_PANEL_POSTS_PAGE_URL = '/posts'
export const ADMIN_PANEL_LANGUAGE_PAGE_URL = '/language'
